import { NextRequest, NextResponse } from 'next/server'

const MOCK_MARKET_DATA = {
  lastUpdated: new Date().toISOString(),
  marketStatus: {
    isOpen: true,
    openTime: '09:30 AM',
    closeTime: '04:00 PM',
    hoursRemaining: 4,
  },
  indices: [
    {
      symbol: 'SPX',
      name: 'S&P 500',
      price: 5300.45,
      change: 45.32,
      changePercent: 0.86,
    },
    {
      symbol: 'INDU',
      name: 'Dow Jones',
      price: 42857.20,
      change: 285.63,
      changePercent: 0.67,
    },
    {
      symbol: 'CCMP',
      name: 'Nasdaq',
      price: 16980.15,
      change: 125.48,
      changePercent: 0.74,
    },
  ],
  topGainers: [
    {
      symbol: 'NVDA',
      name: 'NVIDIA Corporation',
      price: 875.34,
      changePercent: 3.24,
      volume: 45_300_000,
      industry: 'Technology',
    },
    {
      symbol: 'MSFT',
      name: 'Microsoft Corporation',
      price: 416.22,
      changePercent: 2.85,
      volume: 23_100_000,
      industry: 'Technology',
    },
    {
      symbol: 'AAPL',
      name: 'Apple Inc.',
      price: 189.95,
      changePercent: 1.31,
      volume: 52_400_000,
      industry: 'Technology',
    },
    {
      symbol: 'GOOGL',
      name: 'Alphabet Inc.',
      price: 177.45,
      changePercent: 1.23,
      volume: 21_800_000,
      industry: 'Technology',
    },
    {
      symbol: 'META',
      name: 'Meta Platforms Inc.',
      price: 489.23,
      changePercent: 2.15,
      volume: 18_500_000,
      industry: 'Technology',
    },
    {
      symbol: 'AMZN',
      name: 'Amazon.com Inc.',
      price: 186.78,
      changePercent: 1.92,
      volume: 39_200_000,
      industry: 'Consumer Discretionary',
    },
    {
      symbol: 'TSLA',
      name: 'Tesla Inc.',
      price: 242.84,
      changePercent: 2.45,
      volume: 128_500_000,
      industry: 'Automotive',
    },
    {
      symbol: 'PLTR',
      name: 'Palantir Technologies',
      price: 28.95,
      changePercent: 3.12,
      volume: 89_300_000,
      industry: 'Software',
    },
    {
      symbol: 'AVGO',
      name: 'Broadcom Inc.',
      price: 145.67,
      changePercent: 2.38,
      volume: 8_400_000,
      industry: 'Semiconductors',
    },
    {
      symbol: 'NFLX',
      name: 'Netflix Inc.',
      price: 534.89,
      changePercent: 1.87,
      volume: 2_150_000,
      industry: 'Entertainment',
    },
  ],
  topLosers: [
    {
      symbol: 'XLE',
      name: 'Energy Select Sector SPDR',
      price: 85.42,
      changePercent: -2.34,
      volume: 12_300_000,
      industry: 'Energy',
    },
    {
      symbol: 'GLD',
      name: 'SPDR Gold Shares',
      price: 198.75,
      changePercent: -1.89,
      volume: 5_600_000,
      industry: 'Commodities',
    },
    {
      symbol: 'TLT',
      name: 'iShares 20+ Year Treasury',
      price: 92.34,
      changePercent: -2.15,
      volume: 18_900_000,
      industry: 'Bonds',
    },
    {
      symbol: 'FXI',
      name: 'iShares China Large-Cap',
      price: 34.56,
      changePercent: -1.45,
      volume: 22_400_000,
      industry: 'International Equity',
    },
    {
      symbol: 'IYM',
      name: 'iShares U.S. Basic Materials',
      price: 78.23,
      changePercent: -1.72,
      volume: 4_200_000,
      industry: 'Materials',
    },
    {
      symbol: 'XLU',
      name: 'Utilities Select Sector SPDR',
      price: 61.45,
      changePercent: -1.23,
      volume: 3_100_000,
      industry: 'Utilities',
    },
    {
      symbol: 'URA',
      name: 'Global X Uranium ETF',
      price: 28.78,
      changePercent: -2.56,
      volume: 15_400_000,
      industry: 'Energy',
    },
    {
      symbol: 'DBC',
      name: 'Commodities ETF',
      price: 22.34,
      changePercent: -1.98,
      volume: 8_700_000,
      industry: 'Commodities',
    },
    {
      symbol: 'EUO',
      name: 'ProShares UltraShort Euro',
      price: 34.12,
      changePercent: -1.34,
      volume: 1_200_000,
      industry: 'Currencies',
    },
    {
      symbol: 'PUTS',
      name: 'SPX Put ETF',
      price: 12.45,
      changePercent: -3.21,
      volume: 28_500_000,
      industry: 'Derivatives',
    },
  ],
  mostActive: [
    {
      symbol: 'TSLA',
      name: 'Tesla Inc.',
      price: 242.84,
      changePercent: 2.45,
      volume: 128_500_000,
      industry: 'Automotive',
    },
    {
      symbol: 'AAPL',
      name: 'Apple Inc.',
      price: 189.95,
      changePercent: 1.31,
      volume: 52_400_000,
      industry: 'Technology',
    },
    {
      symbol: 'AMZN',
      name: 'Amazon.com Inc.',
      price: 186.78,
      changePercent: 1.92,
      volume: 39_200_000,
      industry: 'Consumer Discretionary',
    },
    {
      symbol: 'PLTR',
      name: 'Palantir Technologies',
      price: 28.95,
      changePercent: 3.12,
      volume: 89_300_000,
      industry: 'Software',
    },
    {
      symbol: 'NVDA',
      name: 'NVIDIA Corporation',
      price: 875.34,
      changePercent: 3.24,
      volume: 45_300_000,
      industry: 'Technology',
    },
    {
      symbol: 'SPY',
      name: 'SPDR S&P 500',
      price: 532.45,
      changePercent: 0.86,
      volume: 78_900_000,
      industry: 'ETF',
    },
    {
      symbol: 'QQQ',
      name: 'Invesco QQQ',
      price: 387.23,
      changePercent: 1.15,
      volume: 65_200_000,
      industry: 'ETF',
    },
    {
      symbol: 'IWM',
      name: 'iShares Russell 2000',
      price: 198.45,
      changePercent: -0.32,
      volume: 34_100_000,
      industry: 'ETF',
    },
    {
      symbol: 'EEM',
      name: 'iShares MSCI Emerging Markets',
      price: 41.23,
      changePercent: 0.54,
      volume: 28_700_000,
      industry: 'ETF',
    },
    {
      symbol: 'GLD',
      name: 'SPDR Gold Shares',
      price: 198.75,
      changePercent: -1.89,
      volume: 5_600_000,
      industry: 'ETF',
    },
  ],
}

export async function GET(request: NextRequest) {
  try {
    // Update timestamp to current time
    const data = {
      ...MOCK_MARKET_DATA,
      lastUpdated: new Date().toISOString(),
    }

    return NextResponse.json(data)
  } catch (error) {
    console.error('Error fetching market data:', error)
    return NextResponse.json(
      { error: 'Failed to fetch market data' },
      { status: 500 }
    )
  }
}
